services:
  database:
     container_name: database
     ports:
       - "8005:1433"
     environment:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Aa13846035"
  crud:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "80:8080"
    depends_on:
      - database


